Set version to 2.0.0, rename hold.ts to holders (as a matter of taste)
Also fix result type of onChanging in the new `ValueHolder<T>`
(else TS demands onChanging implementors return undefined explicitly).

Downgrade TypeScript to 3.6.5 because 3.7 changes output of .d.ts
files for get accessors in classes, which breaks TypeScript 3.5 and
earlier with the following message:

"error TS1086: An accessor cannot be declared in an ambient context."